[toolchain]
# this should match the toolchain as pinned by ariel-os
channel = "nightly-2024-12-10"
targets = [
  "thumbv6m-none-eabi",
  "thumbv7m-none-eabi",
  "thumbv7em-none-eabi",
  "thumbv7em-none-eabihf",
  "thumbv8m.main-none-eabi",
  "riscv32imc-unknown-none-elf",
  "riscv32imac-unknown-none-elf",
]
components = ["rust-src"]
